name: cxr
channels:
  - conda-forge
  - defaults
dependencies:
  - babel
  - imagecodecs
  - imageio
  - ipykernel
  - ipython
  - json5
  - jsonschema
  - matplotlib
  - nodejs
  - numpy
  - opencv
  - pandas
  - pillow
  - scikit-learn
  - scipy
  - scikit-image
  - dicom2nifti
  - nibabel
  - h5py
  - seaborn
  - simpleitk
  - tqdm
  - pip:
    - hiddenlayer
    - tensorflow-gpu